all: part_one part_two

@part_one INPUT="inputs/puzzle.txt": build_one
    ./part_one {{INPUT}}

@part_two INPUT="inputs/puzzle.txt": build_two
    ./part_two {{INPUT}}

build_one:
    rustc --edition 2024 -o part_one part_one.rs

build_two:
    rustc --edition 2024 -o part_two part_two.rs

clean:
    rm part_one part_two
